name: adrenal-scrna
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.11.4
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - scanpy=1.9.6
  - anndata=0.10.7
  - scvelo=0.3.2
  - python-igraph=0.11.4
  - leidenalg=0.10.1
  - h5py=3.11.0
  - umap-learn=0.5.6
  - scikit-learn=1.4.2
  - pip